Agiles Projektmanagement vs. St. Galler Managementmodell
=======================================================
:toc:

= Einleitung
== St. Galler Managementmodell
Das St. Galler Managementmodell ist eine übersicht, wie ein Unternehmen aufgebaut werden kann, und welche Einflüsse von aussen das Unternehmen beinflussen können. Es wird gebraucht, um die Unternehmensstrategie zu entwickeln, da diese von den Interessen der Anspruchsgruppen abhängt. Die Strategie hat direkten Einfluss auf das Leitbild und die Unternehmenskultur. Somit wird das ganze Geschäft von der Unternehmensstrategie gesteuert. 

== Agiles Projektmanagement

= Vergleich
Es ist quasi nicht möglich das St. Galler Managementmodell mit dem Agilen Projektmanagement zu vergleichen. Das Agile Projektmanagement beschreibt eine spezifische Art ein Projekt abzuwickeln. Es muss nicht einmal auf das ganze Untenehmen angewendet werden. Meistens betrifft es nur einzelne Teams, während andere auch mit der Klassischen PM arbeiten. 
Wie die Geschäftsleitung das St. Galler Managementmodell anwendet, welche Schlüsse sie daraus ziehen und wie die Strategie im Endeffekt aussieht ist völlig unterschiedlich. Gehört es zur Strategie, neue Softwareprojekte mit Agilen Methoden abzuwickeln, um die Interssengruppe Mitarbeiter zu befriedigen und eine Zielharmonie zwischen Kunde und Unternehmen zu erzeugen, darf das die Geschäftsleitung selbstverständlich tun. 
Somit ist es gar nicht nötig, wenn überhaupt Sinvoll unterschiede zwischen Agilem PM und dem St. Galler Managementmodell zu ziehen, da sie zwei unterschiedliche Ziele verfolgen. 

== Umwelt der Unternehmung
Projete, welche mit Agilem PM abgewickelt werden können durchaus vorteile für Kunden haben. Es gehört zum Interesse des Kundens, Änderungen in einem Projekt zu wünschen und dass diese durchgesetzt werden. Mit der Agilen PM ist dies für das Unternehmen einfacher handzuhaben und auch mit kleineren Kosten. Der Zielkonflickt zwischen dem Kunden und des Unternehmens bezüglich den Kosten eines Projektes wird somit verkleinert. Zusätzlich wird der Kunde mit regelmässigen releases über den Zwischenstand des Prjektes informiert, und kann fortlaufend weitere Ideen einbringen. Die allgemeine Kundenzufriedenheit profitert im Endeffekt davon. Jedoch liegt die Gefahr bei Agilen Projekten, dass sie sich länger in die Weite ziehen lassen als erwartet. Der Kunde weiss zu beginn nicht wieviel das Projekt effektiv kosten wird, statdessen bekommt er nur eine grobe Schätzung. 

== Innerhalb der Unternehmung
Der Entschied des Managements, Agile PM einzuführen wirkt sich durchaus auch auf die Mitarbeiter aus. 

== In der Führung

== In der Organisation

== In der Verwendung von Führungs-Methoden