Projketziele
===========
Version 1.0, 13.12.2016
:toc:
:numbered:

== Techonlogie
- Die Applikation wird als Webtool implementiert und ist über die üblichen Browser (Chrome, Firefox und Edge) bedienbar.
- Das Tool verfügt über ein Responsive Design, damit der User über seine Tablet und Smartphone mit verschidenen Bildschirmgrössen die Applikation bedienen kann.

== Funktionen
- Damit der User sich authentifizieren kann, wird ein Login mit Username und Passwort implementiert. 
- Neue Nutzer können sich mit ihrem Namen und Email-Adresse registrieren.
- Die Appliaktion ist in Deutsch und Englisch verfügbar, das heisst alle Texte werden sowohl in Englisch oder in Deutsch angezeigt. Der User kann jederzeit wählen,in welcher Sprache das Too, sein soll. 
- Das Tool unterstützt die Verbindung mit den drei Social-Media Plattformen Facebool, Instagram und Twitter.
- Es können Posts mit Bild und Text vorbereitet werden. Diese werden in der Datenbank gespeichert, damit sie von einem anderen Gerät weiterverwendet werden können. Jedem Post kann ein Datum zugewiesen werden, an welchem geplant ist den Post zu veröffentlichen.
- Es wird eine Preview des Accounts mit den Post-entwürfen erstellt. Diese Preview wird anhand der Veröffentlichungsdaten der Postentwürfe erstellt.  
- Mit Google AdSense wird Werbung auf die Webseite geladen. Diese soll subtli sein und darf nicht die Webseite dominieren. 

== Daten
- Die Benutzerdaten werden auf einem SQL-Server abgelegt.
- Die Passwörter der Nutzer sind mit einem aktuellen Hash gehasht und gesaltet.
