Anwendungsfälle
===============
Version 1.0, 29.11.2016
:toc:

[uml]
--
title Timeline

rectangle Client {
    (Kalender mit Posts)
}

rectangle Server {
    (Daten bereitstellen)
}


:User:

User -up-> (Kalender mit Posts)
(Daten bereitstellen) -left-> (Kalender mit Posts)
--
 * Some Fany Stufff fffff about ze Usecase
 ** E tu Seraphe

[uml]
--
title Register

rectangle Client {
    (Register request)
}

rectangle Server {
    (Register)
}

:User:

User -up-> (Register request)
(Register request) -right-> (Register)
--
 * Some Fany Stufff fffff about ze Usecase
 ** E tu Seraphe
 
[uml]
--
title Logout

rectangle Client {
    (Logout request)
}

rectangle Server {
    (Logout)
}

:User:

User -up-> (Logout request)
(Logout request) -right-> (Logout)
--
 * Some Fany Stufff fffff about ze Usecase
 ** E tu Seraphe

[uml]
--
title Login

rectangle Client {
    (Login request)
}

rectangle Server {
    (Login)
}

:User:

User -up-> (Login request)
(Login request) -right-> (Login)
--
 * Some Fany Stufff fffff about ze Usecase
 ** E tu Seraphe

[uml]
--
title Darude Sanddorm

rectangle Client{
    (Beitragsentwurf Erstellen)
    (Beitragsentwurf Bearbeiten)
}

rectangle Server{
    (Beitragsentwurf Speichern)
    (Beitragsentwurf Laden)
}

User --> (Beitragsentwurf Erstellen)
(Beitragsentwurf Erstellen) -> (Beitragsentwurf Speichern)
:Pascal: --> (Beitragsentwurf Bearbeiten)
(Beitragsentwurf Bearbeiten) -> (Beitragsentwurf Laden)
--
* GEEgE
** fuck gueti frag


[uml]

--
 * Some Fany Stufff fffff about ze Usecase
 ** E tu Seraphe