Qualitätssicherung garantieren
==============================
Version 1.1, 13.12.2016
:toc:

== Wieso ist Qualität wichtig?
Zu den Hauptzielen von Qualitätssicherung zählen das Auffinden von Fehlern und das Aufbauen von Vertrauen in die Qualität des erstellten Produkts.
Um diese Ziele zu erreichen, werden in der Regel strukturierte Softwaretests in das Projekt eingeplant.
Diese Tests können automatisch oder manuell durchgeführt werden.

[NOTE]
====
Automatische Tests für Whitebox-Testing (Technisch) und manuelle Tests für Blackbox-Testing (Fachlich) bevorzugt wird.
====

== Vorgehen Agil (Scrum)
Das Scrum-Team, welches ein Scrum-Projekt selbstorganisierend durchführt, stellt das Herzstück des Projekts dar.
Aus diesem Grund ist die Teamzusammenstellung der kritische Erfolgsfaktor für das Projekt.
Aus Sicht der Qualitätssicherung sind hier insbesondere zwei Massnahmen entscheidend:

* Der Product Owner ist jederzeit entscheidungsfähig besitzt die fachliche Kompetenz, um Anforderungen zu priorisieren
* Die Teammitglieder besitzen die Fähigkeiten, welche zur Entwicklung qualitativ hochwertiger Software nötig sind
** Kenntnisse von Designmethoden und der verwendeten Programmiersprache
** Kenntnisse in Methoden der Qualitätssicherung

Dies ist notwendig, da in Scrum keine Tester-Rolle vorgesehen ist.
Es sollten durch das Scrum-Team Vorgaben hinsichtlich der Programmierung in Form von Programmierrichtlinien festgelegt werden, um die Wartbarkeit der Software zu gewährleisten.
Die Einhaltung der Richtlinien sollte automatisiert in Form statischer Analysen im Integrationsprozess geprüft werden, im Idealfall durch eine Continous Integration.
Wir setzten hierzu link:https://codeclimate.com/github/StarlordTheCoder/SocialMediaManager[CodeClimate], welche unseren Code automatisch nach jedem Push analysiert.
Diese Vorgaben bilden zusammen mit den im Team festgelegten Qualitätszielen die <<DoD>>.
Die DoD enthält somit die zentralen Kriterien, die erfüllt werden müssen, damit ein (Zwischen-)Produkt als fertiggestellt betrachtet werden kann.
Qualitätssicherungsmassnahmen während des Sprints dienen der Prüfung des Releases. Neben bereits angesprochenen statischen Analysen sollten als weitere Qualitätssicherung auch ein Review durchgeführt werden. Zu diesem Zweck empfehlenswert ist die Praxis des Pair Programming aus dem Extreme Programming.
Hierbei arbeiten zwei Entwickler am selben Stück Code. Während einer die eigentliche Programmierung vornimmt, prüft der zweite Entwickler den geschriebenen Code per Sichtprüfung.

=== Entwicklungsrichtlinien
* Git-Commits sollten mit der Commit-Nummer beginnen (#NUMMER)
* Code-Cleanup vor Commit ausführen, damit die Coding-Konventionen eingehalten werden

=== Programmierrichtlinien
* Sprach-Konventionen für Klassen, Variablen, Methoden etc. sind eingehalten

[[DoD]]
=== Definition of Done (DoD)
* Alle Akzeptanzkriterien werden erfüllt
* Der Code ist fertiggestellt und im Versionierungssystem eingespielt
* Dokumentation Update durchgeführt
* Es wurde ein Code Review durchgeführt oder der Code wurde im Pair Programming erarbeitet
* Coding Guidelines und Standards wurden eingehalten
* Es wurden Unit Tests durchgeführt und auf "Pass"
* Es sind keine kritischen Bugs offen

== Vergleich Agil & Klassisch
In agile Projekten wird viel Wert auf das Kontinuierliche gesetzt.
Man verbessert das Team durch Reviews und die Software durch iterative Entwicklung und kontinuierliche Integration.
Diese Reflektionen werden nach jedem Sprint, also regelmässig durchgeführt.
Im Klassischen Ansatz werden Testing und Integration erst nach der Implementation durchgeführt, nicht während.
Dadurch fallen kritische Denkfehler in der Integration erst am Schluss des Projektes auf, wo der Aufwand einer Korrektur um ein vielfaches grösser ist.
Dafür ist der Testaufwand im Totalen kleiner, da man nur einmal gross testen muss.
Ob die Qualität am Ende der Entwicklung ausreichend ist werden zu Beginn Qualitätsziele definiert.
Dies kann im klassischen und agilen Projektmanagement getan werden.
Diese Qualitätsziele müssen vor jedem Release erfüllt werden, damit dieser abgenommen wird.
Dieser Qualitätsplan inklusive den Qualitätszielen ist wie alles im Klassischen Ansatz nicht sehr flexibel.
Falls die Qualitätsanforderungen strenger werden, muss dieser Plan in einem aufwändigen Prozess angepasst werden.

== Vorteile Agil
* Schnelle Resultate, falls das Projekt in eine falsche Richtung verläuft
* Regelmässige Qualitätskontrollen aller Funktionen, nicht nur der Zentralen
* Erhöhte Code-Qualität dank Zwei-Augen-Prinzip (Code-Review, Pair-Programming)
* Flexible Änderung der Qualitätsziele